import React from 'react'
import Head from 'next/head'
import Overview from '../../../components/Overview/Overview.js'

const PicturePage = () => (
  <>
    <Head>
      <title>Arthur Paumier - Page Photo</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <Overview />
  </>
)

export async function getStaticPaths(){
  const collections = await collectionService.loadCollections()
  const paths = collections.map(collection => ({params : { slug: collection.slug }}))
  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const pictures = await pictureService.loadPicturesByCollection(params.slug)
  return {
    props: {
       pictures,
    },
  }
}

export default PicturePage
