import Head from 'next/head'
import Grid from '../../components/Grid/Grid.js'
import Script from 'next/script'
import collectionService from '../../services/collectionService'
import pictureService from '../../services/pictureService'
import { useRouter } from 'next/router'

export default function Collection({ pictures }) {

  const router = useRouter()
  const slug = router.query.slug
  const capitalizedSlug = slug.charAt(0).toUpperCase() + slug.slice(1)

  return (
    <>
      <Head>
        <title key='title'>{process.env.NEXT_PUBLIC_APP_TITLE} | {capitalizedSlug}</title>
        <meta key='description' name='description' content='Generated by create next app' />
      </Head>
      <Grid pictures={pictures} />
    </>
  )
}

export async function getStaticPaths(){
  const collections = await collectionService.loadCollections()
  const paths = collections.map(collection => ({params : { slug: collection.slug }}))
  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const pictures = await pictureService.loadPicturesByCollection(params.slug)
  return {
    props: {
       pictures,
    },
  }
}
