import Head from 'next/head'
import Stripe from '../components/Stripe/Stripe.js'
import ArrowButton from '../components/ArrowButton/ArrowButton.js'
import { useEffect, useState, useRef } from 'react'
import collectionService from '../services/collectionService'

const Home = ({ collections }) => {
  const [isVisible, setIsVisible] = useState(true)
  const [count, setCount] = useState(0)
  const [isMobile, setIsMobile] = useState(false)

  const handleScroll = e => {
    setCount(e.target.scrollLeft)
    if (count > 60) {
      setIsVisible(false)
    }
  }

  const handleResize = () => {
    document.documentElement.clientWidth < 768
      ? setIsMobile(true)
      : setIsMobile(false)
  }

  useEffect(() => {
    window.addEventListener('resize', handleResize)
    handleResize()
    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [])

  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_APP_TITLE} | Site internet</title>
        <meta key='description' name='description' content='Generated by create next app' />
        <link rel='icon' href='./images/logo.png' key='favicon' />
      </Head>
      <div className='collection-list' onScroll={isVisible ? handleScroll : undefined}>
        {collections?.map(collection => (
          <Stripe
            key={collection?.id}
            isMobile={isMobile}
            slug={collection?.slug}
            name={collection?.name}
            desktop_img_url={collection?.acf.desktop_image}
            mobile_img_url={collection?.acf.mobile_image ? collection.acf.mobile_image : ''}
          />
        ))}
        <ArrowButton isVisible={isVisible} />
      </div>
    </>
  )
}

export async function getStaticProps() {
  const collections = await collectionService.loadCollections()

  return {
    props: {
      collections,
    },
  }
}

export default Home
