import Head from 'next/head'
import Layout from '../components/Layout/Layout.js'
import Stripe from '../components/Stripe/Stripe.js'
import ArrowButton from '../components/ArrowButton/ArrowButton.js'
import Link from 'next/link'
import { useState } from 'react'
import collectionService from '../services/collectionService'

const Home = ({ collections }) => {
  // const [isVisible, setIsVisible] = useState(true)
  // const [count, setCount] = useState(0)
  // const handleScroll = e => {
  //   setCount(e.target.scrollLeft)
  //   if (count > 60) {
  //     setIsVisible(false)
  //     e.target.removeEventListener('scroll', handleScroll)
  //   }
  // }

  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_APP_TITLE} | Site internet</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./images/logo.png' />
      </Head>
      <div className='collection-list' /*onScroll={handleScroll}*/>
        {collections?.map(collection => (
          <Stripe
            key={collection?.id}
            slug={collection?.slug}
            name={collection?.name}
            desktop_img_url={collection?.acf.desktop_image}
            mobile_img_url={collection?.acf.mobile_image ? collection.acf.mobile_image : ''}
          />
        ))}
        {/* <ArrowButton isVisible={isVisible} /> */}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const collections = await collectionService.loadCollections()

  return {
    props: {
      collections,
    },
  }
}

export default Home
