import Head from "next/head";
import Layout from "../components/Layout/Layout.js"
import Stripe from "../components/Stripe/Stripe.js"
import ArrowButton from '../components/ArrowButton/ArrowButton.js';
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Layout>
        <Stripe name='landscape' img='https://live.staticflickr.com/65535/51505029420_8315691cd3_h.jpg' />
        <Stripe name='street-photo' img='https://live.staticflickr.com/65535/51953115414_a2298c6e5b_h.jpg'/>
        <Stripe name='abstract' img='https://live.staticflickr.com/65535/50936570622_209d1cf522_h.jpg' />
        <Stripe name='organic' img='https://live.staticflickr.com/65535/52011985367_f4d1323004_h.jpg' />
        <Stripe name='architecture' img='https://live.staticflickr.com/65535/51119857068_61eb2279ac_h.jpg' />
        <ArrowButton />
      </Layout>
    </>
  );
}
