import React from 'react'
import Head from 'next/head'
import Overview from '../../../../components/Overview/Overview.js'
import collectionService from '../../../../services/collectionService'
import pictureService from '../../../../services/pictureService'
import PropTypes from 'prop-types'

const PicturePage = ({ pictureData }) => (
  <>
    <Head>
      <title>Arthur Paumier - Page Photo</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <Overview pictureData={pictureData} />
  </>
)

export async function getStaticPaths(){
  const collections = await collectionService.loadCollections()

  const paths = await Promise.all(collections.map(async collection => {
    const pictures = await pictureService.loadPicturesByCollection(collection.slug)
    return pictures.map(picture => ({ params: { slug: collection.slug, id: picture.id.toString() } }))
  })).then(res => res.flat())

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const pictureData = await pictureService.loadPictureById(params.id)
  return {
    props: {
       pictureData,
    },
  }
}

PicturePage.propTypes = {
  pictureData: PropTypes.object.isRequired,
}

export default PicturePage
